import type { TrackEffect, TrackEffectType, EqBand } from "@/types";
import { defaultEq3Bands, defaultEq4Bands, makeTrackEffect } from "@/lib/effects";

type Props = { effects: TrackEffect[]; onChange: (effects: TrackEffect[]) => void; };
const effectTypes: { type: TrackEffectType; label: string }[] = [{ type: "eq", label: "EQ" }, { type: "reverb", label: "Reverb" }, { type: "overdrive", label: "Overdrive" }, { type: "distortion", label: "Distortion" }, { type: "compressor", label: "Compressor" }];
const setParam = (effect: TrackEffect, key: string, value: unknown): TrackEffect => ({ ...effect, params: { ...effect.params, [key]: value } });
const num = (v: unknown, f: number) => typeof v === "number" ? v : f;

export default function FXRack({ effects, onChange }: Props) {
  const update = (id: string, next: TrackEffect) => onChange(effects.map((fx) => fx.id === id ? next : fx));
  const move = (index: number, dir: -1 | 1) => { const copy = [...effects]; const target = index + dir; if (target < 0 || target >= copy.length) return; [copy[index], copy[target]] = [copy[target], copy[index]]; onChange(copy); };
  return <section className="fx-rack"><div className="fx-header"><div><p className="eyebrow">FX Rack</p><small>Simple per-track chain. Add the same FX more than once.</small></div><select aria-label="Add FX" onChange={(e) => { if (!e.target.value) return; onChange([...effects, makeTrackEffect(e.target.value as TrackEffectType)]); e.target.value = ""; }}><option value="">+ Add FX</option>{effectTypes.map((fx) => <option key={fx.type} value={fx.type}>{fx.label}</option>)}</select></div><div className="nudge-row"><button type="button" onClick={() => onChange(effects.map((fx) => ({ ...fx, enabled: false })))}>Bypass All FX</button><button type="button" onClick={() => onChange([])}>Remove All FX</button></div>{effects.length === 0 && <p className="hint">No FX yet. Add EQ, reverb, drive, distortion, or compressor.</p>}{effects.map((effect, index) => <div className="fx-module" key={effect.id}><div className="fx-module-title"><label><input type="checkbox" checked={effect.enabled} onChange={(e) => update(effect.id, { ...effect, enabled: e.target.checked })} /> {effect.name}</label><span><button type="button" onClick={() => move(index, -1)}>↑</button><button type="button" onClick={() => move(index, 1)}>↓</button><button type="button" onClick={() => onChange([...effects, { ...effect, id: `${effect.type}-${Date.now()}` }])}>Duplicate</button><button type="button" onClick={() => onChange(effects.filter((fx) => fx.id !== effect.id))}>Remove</button></span></div><EffectParams effect={effect} onChange={(next) => update(effect.id, next)} /></div>)}</section>;
}

function EffectParams({ effect, onChange }: { effect: TrackEffect; onChange: (effect: TrackEffect) => void }) {
  if (effect.type === "eq") {
    const bands = (Array.isArray(effect.params.bands) ? effect.params.bands : defaultEq3Bands()) as EqBand[];
    return <div><label className="field-label">Band Count<select value={num(effect.params.bandCount, 3)} onChange={(e) => onChange(setParam(setParam(effect, "bandCount", Number(e.target.value)), "bands", Number(e.target.value) === 4 ? defaultEq4Bands() : defaultEq3Bands()))}><option value={3}>3-band</option><option value={4}>4-band</option></select></label><div className="eq-preview">TODO: full EQ curve preview later</div>{bands.map((band, i) => <div className="eq-band" key={band.label}><strong>{band.label}</strong>{(["frequencyHz", "gainDb", "q"] as const).map((key) => <label className="slider-control compact" key={key}><span className="slider-label"><strong>{key === "frequencyHz" ? "Frequency" : key === "gainDb" ? "Gain" : "Q"}</strong><em>{band[key]}</em></span><input type="range" min={key === "frequencyHz" ? 20 : key === "gainDb" ? -24 : 0.1} max={key === "frequencyHz" ? 20000 : key === "gainDb" ? 24 : 10} step={key === "frequencyHz" ? 10 : 0.1} value={band[key]} onChange={(e) => { const next = bands.map((b, bi) => bi === i ? { ...b, [key]: Number(e.target.value) } : b); onChange(setParam(effect, "bands", next)); }} /></label>)}</div>)}</div>;
  }
  const ranges: Record<string, [number, number, number]> = effect.type === "reverb" ? { wet: [0, 1, 0.01], decay: [0.1, 10, 0.1], preDelay: [0, 1, 0.01] } : effect.type === "overdrive" ? { drive: [0, 1, 0.01], tone: [100, 8000, 10], wet: [0, 1, 0.01] } : effect.type === "distortion" ? { amount: [0, 1, 0.01], wet: [0, 1, 0.01] } : { threshold: [-60, 0, 1], ratio: [1, 20, 0.1], attack: [0.001, 0.5, 0.001], release: [0.01, 2, 0.01], makeupGain: [0, 24, 0.5] };
  return <>{Object.entries(ranges).map(([key, [min, max, step]]) => <label className="slider-control compact" key={key}><span className="slider-label"><strong>{key}</strong><em>{num(effect.params[key], min)}</em></span><input type="range" min={min} max={max} step={step} value={num(effect.params[key], min)} onChange={(e) => onChange(setParam(effect, key, Number(e.target.value)))} /></label>)}</>;
}
