"use client";

import { useMemo, useState, type ReactNode } from "react";
import { playHtmlAudioFallback, previewPitchedNotes } from "@/lib/audioEngine";
import { downloadBlob, renderPitchedNotesWav, safeFilename } from "@/lib/renderWav";
import { markSampleDuration } from "@/lib/sampleDuration";
import { buildChord, buildNoteRange, CHORD_TYPES, CHROMATIC_NOTES, formatChordLabel, midiToNote, noteToMidi, type ChordType } from "@/lib/musicTheory";
import type { GuitarLabEffects, GuitarLabMode, NoteDuration, Sample, SequencerTrack } from "@/types";

type FretNote = { stringIndex: number; fret: number; note: string; midi: number };
type Props = { samples: Sample[]; bpm: number; track?: SequencerTrack; selectedStepIndex?: number; onStepNotesChange: (trackId: number, stepIndex: number, notes: string[]) => void; onAddRenderedSample: (sample: Sample) => void; onStatus: (message: string) => void; };
const standardTuning = ["E2", "A2", "D3", "G3", "B3", "E4"];
const stripOctave = (note: string) => note.replace(/-?\d+$/, "");
const defaultFx: GuitarLabEffects = { volume: 1, pitchOffsetSemitones: 0, reverbWet: 0, delayWet: 0, drive: 0, chorusWet: 0 };
function Section({ title, children, defaultOpen = true }: { title: string; children: ReactNode; defaultOpen?: boolean }) { const [open, setOpen] = useState(defaultOpen); return <section className="guitar-tool-section"><button className="collapse-title" type="button" onClick={() => setOpen(!open)}>{open ? "▾" : "▸"} {title}</button>{open ? children : null}</section>; }

export default function GuitarTools({ samples, bpm, track, selectedStepIndex, onStepNotesChange, onAddRenderedSample, onStatus }: Props) {
  const [sourceId, setSourceId] = useState("");
  const [mode, setMode] = useState<GuitarLabMode>("chord");
  const [noteDuration, setNoteDuration] = useState<NoteDuration>("1/8");
  const [root, setRoot] = useState("G");
  const [octave, setOctave] = useState(3);
  const [chordType, setChordType] = useState<ChordType>("major");
  const [selectedNotes, setSelectedNotes] = useState<string[]>([]);
  const [selectedFrets, setSelectedFrets] = useState<FretNote[]>([]);
  const [fx, setFx] = useState<GuitarLabEffects>(defaultFx);
  const [tab, setTab] = useState(`e|----------------|\nB|----------------|\nG|----------------|\nD|----------------|\nA|----------------|\nE|----------------|`);
  const source = samples.find((sample) => sample.id === sourceId);
  const chordNotes = useMemo(() => buildChord(`${root}${octave}`, chordType), [root, octave, chordType]);
  const playableNotes = selectedNotes.length ? selectedNotes : chordNotes;
  const rootNote = `${root}${octave}`;
  const canSend = Boolean(track && track.mode === "keyboard" && selectedStepIndex !== undefined);
  const fretKey = (stringIndex: number, fret: number) => `${stringIndex}:${fret}`;
  const selectedFretKeys = new Set(selectedFrets.map((item) => fretKey(item.stringIndex, item.fret)));
  const selectedNoteSet = new Set(selectedNotes);
  const chordPitchClasses = new Set(chordNotes.map(stripOctave));
  const sourceWarning = source?.loadStatus === "decode failed" ? "This sample cannot be pitch-rendered until converted to PCM WAV." : undefined;
  function setChordSelection(notes = chordNotes) { setSelectedNotes(notes); setSelectedFrets([]); }
  async function preview(notes = playableNotes) { if (!source) { onStatus("Select a source sample to preview or render chords."); return; } const result = await previewPitchedNotes({ sample: source, rootNote, notes, mode, bpm, noteDuration, effects: fx }); if (result.status === "decode-failed") { await playHtmlAudioFallback(source); onStatus(sourceWarning ?? result.message); } else onStatus(result.message); }
  async function render(notes = playableNotes, download = false) { if (!source) { onStatus("Select a source sample to preview or render chords."); return; } try { const rendered = await renderPitchedNotesWav({ sample: source, rootNote, notes, mode, bpm, noteDuration, volume: fx.volume, pitchOffsetSemitones: fx.pitchOffsetSemitones }); const timestamp = Date.now(); const notesName = notes.map(stripOctave).join("-").toLowerCase() || timestamp; const name = mode === "chord" ? `guitar_chord_${notesName}` : `guitar_riff_${timestamp}`; const filename = `${safeFilename(name)}.wav`; const objectUrl = URL.createObjectURL(rendered.blob); onAddRenderedSample(markSampleDuration({ id: `guitar-render-${timestamp}`, name, filename, type: rendered.durationSeconds > 2 ? "loop" : "oneshot", category: "guitar", path: objectUrl, isRendered: true, source: "in-app" }, rendered.durationSeconds)); if (download) downloadBlob(rendered.blob, filename); onStatus(download ? "Rendered Guitar Lab sample and downloaded WAV. FX render is volume/pitch only for now." : "Rendered Guitar Lab sample into the Sample Library. FX render is volume/pitch only for now."); } catch (error) { onStatus(error instanceof Error ? error.message : "Could not render Guitar Lab WAV."); } }
  function send(notes = playableNotes) { if (!track || selectedStepIndex === undefined || track.mode !== "keyboard") { onStatus("Switch selected track to Keyboard mode to send notes."); return; } if (mode === "chord") onStepNotesChange(track.id, selectedStepIndex, notes); else { let overflow = false; notes.forEach((note, index) => { const step = selectedStepIndex + index; if (step >= track.steps.length) { overflow = true; return; } onStepNotesChange(track.id, step, [note]); }); if (overflow) onStatus("Riff reached the last step and stopped before overflowing."); } }
  function toggleNote(note: string) { setSelectedNotes((old) => { const removing = old.includes(note); if (removing) setSelectedFrets((frets) => frets.filter((item) => item.note !== note)); return removing ? old.filter((n) => n !== note) : [...old, note]; }); }
  function toggleFret(stringIndex: number, fret: number) { const midi = noteToMidi(standardTuning[stringIndex]) + fret; const item = { stringIndex, fret, note: midiToNote(midi), midi }; toggleNote(item.note); setSelectedFrets((old) => old.some((n) => n.stringIndex === stringIndex && n.fret === fret) ? old.filter((n) => !(n.stringIndex === stringIndex && n.fret === fret)) : [...old, item]); }
  function clearSelected() { setSelectedNotes([]); setSelectedFrets([]); }
  return <div className="guitar-tools"><div className="control-grid compact-grid"><label>Mode<select value={mode} onChange={(e) => setMode(e.target.value as GuitarLabMode)}><option value="chord">Chord</option><option value="riff">Riff</option></select></label>{mode === "riff" && <label>Note Duration<select value={noteDuration} onChange={(e) => setNoteDuration(e.target.value as NoteDuration)}><option>1/4</option><option>1/8</option><option>1/16</option></select></label>}</div><p className="hint">{mode === "chord" ? "Chord: selected notes play together." : "Riff: selected notes play in order."}</p>
    <Section title="Source"><label className="field-label">Source Sample<select value={sourceId} onChange={(e) => setSourceId(e.target.value)}><option value="">Select source…</option>{samples.filter((s) => s.type === "oneshot" || s.type === "loop" || s.isRendered).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{source ? <p className="hint"><strong>{source.name}</strong><br />{source.type} · {source.category}{source.durationSeconds ? ` · ${source.durationSeconds.toFixed(2)}s` : " · duration unknown"}<br />Status: {source.loadStatus ?? "not loaded"}</p> : <p className="hint">Select a source sample to preview or render chords.</p>}{sourceWarning && <p className="warning-text">{sourceWarning}</p>}</Section>
    <Section title="Chord Helper"><div className="control-grid compact-grid"><label>Root<select value={root} onChange={(e) => setRoot(e.target.value)}>{CHROMATIC_NOTES.map((n) => <option key={n}>{n}</option>)}</select></label><label>Type<select value={chordType} onChange={(e) => setChordType(e.target.value as ChordType)}>{CHORD_TYPES.map((t) => <option key={t}>{t}</option>)}</select></label><label>Octave<select value={octave} onChange={(e) => setOctave(Number(e.target.value))}>{[1,2,3,4,5].map((o) => <option key={o}>{o}</option>)}</select></label></div><p className="chord-preview"><strong>{formatChordLabel(rootNote, chordType)}</strong> = {chordNotes.join(" ")}</p><div className="nudge-row"><button onClick={() => { setChordSelection(); void preview(chordNotes); }}>Preview Chord</button><button onClick={() => { setChordSelection(); void render(chordNotes); }}>Render Chord</button><button onClick={() => { setChordSelection(); send(chordNotes); }} disabled={!canSend}>Send Chord to Selected Step</button></div></Section>
    <Section title="Fretboard / Piano"><div className="fretboard"><div className="fret-numbers"><span />{Array.from({ length: 13 }, (_, fret) => <span key={fret}>{fret}</span>)}</div><div className="fret-markers"><span />{Array.from({ length: 13 }, (_, fret) => <span key={fret} className="marker-cell">{[3,5,7,9].includes(fret) && <i />} {fret === 12 && <><i /><i /></>}</span>)}</div>{standardTuning.slice().reverse().map((openNote, rev) => { const stringIndex = standardTuning.length - 1 - rev; return <div className="fret-string" key={openNote}><span className="string-name">{openNote.replace("4", "e").replace(/\d/, "")}</span>{Array.from({ length: 13 }, (_, fret) => { const note = midiToNote(noteToMidi(openNote) + fret); const selected = selectedNoteSet.has(note) || selectedFretKeys.has(fretKey(stringIndex, fret)); const suggested = chordPitchClasses.has(stripOctave(note)); return <button type="button" key={fret} className={`fret ${fret === 0 ? "open" : ""} ${selected ? "selected" : suggested ? "active" : ""}`} onClick={() => toggleFret(stringIndex, fret)}>{selected || suggested || fret === 0 ? stripOctave(note) : ""}</button>; })}</div>; })}</div><div className="piano-keyboard">{buildNoteRange("C3", 2).map((note) => <button key={note} type="button" className={`piano-key ${note.includes("#") ? "black" : "white"} ${selectedNoteSet.has(note) ? "selected" : chordPitchClasses.has(stripOctave(note)) ? "active" : ""}`} onClick={() => toggleNote(note)}>{stripOctave(note)}</button>)}</div><p className="chord-selected">Selected: <strong>{selectedNotes.length ? selectedNotes.join(" ") : "none"}</strong></p><div className="nudge-row"><button onClick={clearSelected}>Clear Selected Notes</button><button onClick={() => send()}>Send to Selected Step</button><button onClick={() => void preview()}>Preview Selected Notes</button><button onClick={() => void render()}>Render to New Sample</button></div></Section>
    <Section title="Guitar Lab FX" defaultOpen={false}><div className="slider-stack">{([['volume',0,1.5,.01],['pitchOffsetSemitones',-24,24,1],['reverbWet',0,1,.01],['delayWet',0,1,.01],['drive',0,1,.01],['chorusWet',0,1,.01]] as const).map(([key,min,max,step]) => <label className="slider-control compact" key={key}><span className="slider-label">{key} <em>{fx[key]}</em></span><input type="range" min={min} max={max} step={step} value={fx[key]} onChange={(e) => setFx((old) => ({ ...old, [key]: Number(e.target.value) }))} /></label>)}</div><button onClick={() => setFx(defaultFx)}>Reset Guitar FX</button><p className="hint">Preview uses these FX where routing is supported. Render currently applies volume and pitch offset; time FX are TODO/bypass.</p></Section>
    <Section title="Tab Scratchpad" defaultOpen={false}><textarea className="tab-scratchpad" value={tab} onChange={(e) => setTab(e.target.value)} rows={6} spellCheck={false} /><div className="nudge-row"><button onClick={() => setTab("")}>Clear Tab</button><button onClick={() => setTab((old) => `${old}\n${formatChordLabel(rootNote, chordType)} (${chordNotes.join(" ")})`)}>Insert Chord Name</button><button onClick={() => navigator.clipboard?.writeText(tab)}>Copy Tab to Clipboard</button></div></Section>
  </div>;
}
