"use client";

import { useEffect, useState } from "react";
import SampleWaveform from "@/components/SampleWaveform";
import { createEqualSlices, SLICE_COLORS } from "@/lib/slices";
import type { Sample, Slice } from "@/types";

type Props = { selectedSample?: Sample; onEnsureDuration: (sample: Sample) => Promise<Sample>; onPreviewSample: (sample: Sample) => void; onPreviewSlice: (slice: Slice) => void; onStopPreview: () => void; onCreateSlicedTrack: (sample: Sample, slices: Slice[]) => void; onStatus: (message: string) => void; };
const fmt = (ms: number) => `${Math.round(ms)} ms`;
export default function WaveformSlicer({ selectedSample, onEnsureDuration, onPreviewSample, onPreviewSlice, onStopPreview, onCreateSlicedTrack, onStatus }: Props) {
  const [parts, setParts] = useState(4); const [slices, setSlices] = useState<Slice[]>([]); const [selectedSliceId, setSelectedSliceId] = useState<string>();
  useEffect(() => { setSlices([]); setSelectedSliceId(undefined); }, [selectedSample?.id]);
  async function split() { if (!selectedSample) { onStatus("Select a sample from the Sample Library first."); return; } const loaded = await onEnsureDuration(selectedSample); const result = createEqualSlices(loaded, parts); if (result.error) { onStatus(result.error); return; } setSlices(result.slices); setSelectedSliceId(result.slices[0]?.id); onStatus(`Created ${result.slices.length} equal slices.`); }
  function updateSlice(id: string, patch: Partial<Slice>) { setSlices((old) => old.map((slice) => slice.id === id ? { ...slice, ...patch } : slice)); }
  function addFullSlice() { if (!selectedSample?.durationMs) { onStatus("Load/decode sample before slicing."); return; } const next = slices.length + 1; const slice = { id: `slice-${Date.now()}`, name: `Slice ${next}`, startMs: 0, endMs: selectedSample.durationMs, fadeInMs: 0, fadeOutMs: 5, attackMs: 0, color: SLICE_COLORS[(next - 1) % SLICE_COLORS.length] }; setSlices((old) => [...old, slice]); setSelectedSliceId(slice.id); }
  return <div className="slicer-panel"><div className="slicer-header"><div><strong>{selectedSample?.name ?? "No sample selected"}</strong><small>{selectedSample ? `${selectedSample.filename} · ${selectedSample.durationSeconds ? `${selectedSample.durationSeconds.toFixed(2)}s` : "duration not loaded"}` : "Select a sample to slice."}</small></div><div className="slicer-actions"><button onClick={() => selectedSample && onPreviewSample(selectedSample)} disabled={!selectedSample}>Preview Sample</button><button onClick={onStopPreview}>Stop Preview</button><button onClick={() => { setSlices([]); setSelectedSliceId(undefined); }}>Clear Slices</button></div></div><SampleWaveform sample={selectedSample} slices={slices} selectedSliceId={selectedSliceId} /><div className="slicer-actions"><label className="field-label">Equal Split<select value={parts} onChange={(e) => setParts(Number(e.target.value))}>{[2,4,8,16].map((n) => <option key={n} value={n}>{n}</option>)}</select></label><button onClick={split} disabled={!selectedSample}>Split</button><button onClick={addFullSlice} disabled={!selectedSample}>Add Slice from Current Region</button><button onClick={() => selectedSample && onCreateSlicedTrack(selectedSample, slices)} disabled={!selectedSample || !slices.length}>Create Sliced Track</button></div><div className="slice-list">{slices.map((slice) => <article className="slice-row" key={slice.id} onClick={() => setSelectedSliceId(slice.id)}><span className="slice-dot" style={{ background: slice.color }} /><strong>{slice.name}</strong><small>{fmt(slice.startMs)} → {fmt(slice.endMs)}</small><label>Attack <input type="number" min={0} value={slice.attackMs ?? 0} onChange={(e) => updateSlice(slice.id, { attackMs: Number(e.target.value) })} /></label><label>Fade in <input type="number" min={0} value={slice.fadeInMs} onChange={(e) => updateSlice(slice.id, { fadeInMs: Number(e.target.value) })} /></label><label>Fade out <input type="number" min={0} value={slice.fadeOutMs} onChange={(e) => updateSlice(slice.id, { fadeOutMs: Number(e.target.value) })} /></label><button onClick={(e) => { e.stopPropagation(); onPreviewSlice(slice); }}>Preview</button><button onClick={(e) => { e.stopPropagation(); setSlices((old) => old.filter((item) => item.id !== slice.id)); }}>Remove</button></article>)}{!slices.length && <p className="hint">Use Equal Split to create 2, 4, 8, or 16 slices.</p>}</div></div>;
}
